name: Deploy Worker

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: cloudflare/serverless-action@master
      with:
        CLOUDFLARE_AUTH_KEY: ${{ secrets.CLOUDFLARE_AUTH_KEY }}
      env:
        CLOUDFLARE_AUTH_EMAIL: ${{ secrets.CLOUDFLARE_AUTH_EMAIL }}
        CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
        CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        CLOUDFLARE_SCRIPT_NAME: ${{ secrets.CLOUDFLARE_SCRIPT_NAME }}
